# SPDX-FileCopyrightText: © 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
  become: true

- name: Disable nouveau drivers
  ansible.builtin.import_tasks: nouveau-disable.yml

- name: Install NVIDIA GRID drivers
  ansible.builtin.include_tasks: nvidia-grid.yml
  when: nvidia_driver_type == "grid"
        and not nvidia_skip_driver_install

- name: Install NVIDIA Tesla drivers
  ansible.builtin.include_tasks: nvidia-tesla.yml
  when: nvidia_driver_type == "tesla"
        and not nvidia_skip_driver_install

- name: Install NVIDIA CUDA drivers
  ansible.builtin.include_tasks: nvidia-cuda.yml
  when: nvidia_driver_type == "cuda"
        and not nvidia_skip_driver_install

- name: Configure X11
  ansible.builtin.import_tasks: x11.yml

- name: Configure nvidia-container
  ansible.builtin.include_tasks: nvidia-container.yml
  when: nvidia_install_container
