# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Apt update cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600 # 1 hr
  become: true

- name: Uninstall NVIDIA drivers
  when: nvidia_driver_uninstall
  ansible.builtin.include_tasks: nvidia-uninstall.yml

- name: Disable nouveau drivers
  when: nvidia_driver_install
  ansible.builtin.include_tasks: nouveau-disable.yml

- name: Install NVIDIA GRID drivers
  when: nvidia_driver_install and nvidia_driver_type == "grid"
  ansible.builtin.include_tasks: nvidia-grid.yml

- name: Install NVIDIA Tesla drivers
  when: nvidia_driver_install and nvidia_driver_type == "tesla"
  ansible.builtin.include_tasks: nvidia-tesla.yml

- name: Install NVIDIA CUDA drivers
  when: nvidia_driver_install and nvidia_driver_type == "cuda"
  ansible.builtin.include_tasks: nvidia-cuda.yml

- name: Install NVIDIA open drivers
  when: nvidia_driver_install and nvidia_driver_type == "open"
  ansible.builtin.include_tasks: nvidia-open.yml

- name: Configure nvidia-container
  when: nvidia_install_container
  ansible.builtin.include_tasks: nvidia-container.yml

- name: Perform scheduled reboot
  ansible.builtin.import_tasks: reboot.yml
