# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Blacklist nouveau driver module
  with_items:
    - vga16fb
    - nouveau
    - rivafb
    - nvidiafb
    - rivatv
  notify: "xronos_nvidia_drivers_ansible : Schedule reboot"
  become: true
  community.general.kernel_blacklist:
    name: "{{ item }}"
    state: present

- name: Modify grub to blacklist nouveau
  notify: "xronos_nvidia_drivers_ansible : Schedule reboot"
  register: grub
  become: true
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="rdblacklist=nouveau"'

- name: Update grub
  when: grub.changed
  become: true
  ansible.builtin.command:
    cmd: update-grub

- name: Perform scheduled reboot
  ansible.builtin.import_tasks: reboot.yml
