# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
- name: Query NVIDIA driver version
  register: _nvidia_driver_query
  failed_when: false
  changed_when: false
  ansible.builtin.command:
    cmd: nvidia-smi --query-gpu=driver_version --format=csv,noheader

- name: Apt install linux headers and dependencies
  become: true
  ansible.builtin.apt:
    pkg:
      - linux-headers-{{ ansible_kernel }}
      - gcc
      - make
      - pkg-config
      - dkms

- name: Apt install cuda keyring
  register: cuda_keyring
  become: true
  ansible.builtin.apt:
    # repo format is distro + version without a period, i.e. ubuntu2204/x86_64
    deb: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_distroversion }}/{{ ansible_architecture }}/cuda-keyring_1.1-1_all.deb"

- name: Install NVIDIA Tesla driver version {{ nvidia_tesla_version}}
  when: nvidia_tesla_version not in _nvidia_driver_query.stdout
  block:
    - name: Stat ~/.cache
      register: _cache_folder_query
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.cache"

    - name: Create ~/.cache
      when: not _cache_folder_query.stat.exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.cache"
        state: directory
        mode: u=rwx,g=,o=

    - name: Download NVIDIA Tesla driver version {{ nvidia_tesla_version}}
      ansible.builtin.get_url:
        url: https://us.download.nvidia.com/tesla/{{ nvidia_tesla_version}}/NVIDIA-Linux-x86_64-{{ nvidia_tesla_version}}.run
        dest: "{{ ansible_env.HOME }}/.cache/NVIDIA-Linux-x86_64-{{ nvidia_tesla_version }}.run"
        mode: ug+x

    - name: Install NVIDIA Tesla driver {{ nvidia_tesla_version }}
      notify: "xronos_nvidia_drivers_ansible : Schedule reboot"
      become: true
      ansible.builtin.shell:
        chdir: "{{ ansible_env.HOME }}/.cache"
        executable: /bin/sh
        cmd: "{{ ansible_env.HOME }}/.cache/NVIDIA-Linux-x86_64-{{ nvidia_tesla_version }}.run --accept-license --no-questions --run-nvidia-xconfig --dkms --disable-nouveau --silent --allow-installation-with-running-driver --install-libglvnd"

    - name: Verify NVIDIA driver version
      register: _nvidia_driver_query
      failed_when: _nvidia_driver_query.stdout != nvidia_tesla_version
      changed_when: false
      ansible.builtin.command:
        cmd: nvidia-smi --query-gpu=driver_version --format=csv,noheader
