---
# see https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/install-nvidia-driver.html#nvidia-GRID-driver
- name: Apt install linux headers and dependencies
  ansible.builtin.apt:
    pkg:
      - linux-headers-{{ ansible_kernel }}
      - gcc
      - make
      - pkg-config
    state: latest
  become: true
  notify: Restart server

- name: Download NVIDIA GRID driver version {{ nvidia_grid_version}}
  ansible.builtin.get_url:
    url: https://us.download.nvidia.com/XFree86/Linux-x86_64/{{ nvidia_grid_version }}/NVIDIA-Linux-x86_64-{{ nvidia_grid_version }}.run
    dest: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_grid_version }}.run
    mode: ug+x

- name: Install NVIDIA GRID drivers
  ansible.builtin.shell:
    chdir: /tmp/
    executable: /bin/sh
    cmd: /tmp/NVIDIA-Linux-x86_64-{{ nvidia_grid_version }}.run --accept-license --no-questions --silent --install-libglvnd
    creates: /usr/bin/nvidia-smi
  become: true
  notify: Restart server
