# SPDX-FileCopyrightText: (c) 2024 Xronos Inc.
# SPDX-License-Identifier: BSD-3-Clause
---
# see https://docs.nvidia.com/datacenter/tesla/tesla-installation-notes/index.html#package-manager
# see https://docs.nvidia.com/datacenter/tesla/drivers/index.html

- name: Apt install cuda keyring
  become: true
  register: cuda_keyring
  ansible.builtin.apt:
    # repo format is distro + version without a period, i.e. ubuntu2204/x86_64
    deb: "https://developer.download.nvidia.com/compute/cuda/repos/{{ nvidia_distroversion }}/{{ ansible_architecture }}/cuda-keyring_1.1-1_all.deb"

- name: Apt update cache
  when: cuda_keyring.changed
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Apt install NVIDIA CUDA drivers
  become: true
  notify: "xronos_nvidia_drivers_ansible : Schedule reboot"
  ansible.builtin.apt:
    pkg:
      - cuda-toolkit-{{ nvidia_cuda_release }}
